### PR TITLE
Typo fix on chiperText variable

### PR DESCRIPTION
**Pull request by TiagoGouvea**
Just fixing typo on variable name.

### CODE REVIEW

**Comment by lil5** [comment]
<https://en.wikipedia.org/wiki/Cipher>
As the variables are in English I'm suggesting @danang-id not to merge this.
:-1:

**Comment by danang-id** [comment]
I think I understand which variables name @TiagoGouvea  is pointing to. It should be `decipherText` instead of `cipherText`. However, your commit doesn't fix the variable name.

**Comment by danang-id** [comment]
Agree with @lil5 . I'm not going to merge this.

**Comment by taufnrsyd** [comment]
I think there is indeed a typo on the variable's name on the example.

```javascript
// this `chiperText` should've been `cipherText`
var chiperText = simpleCrypto.encrypt(plainText);
```

**Pull request closed without merging**
