### PR TITLE
Simplify build and packaging

### LINKED ISSUE #3: Type error when using Typescript
Hi,

I recently tried to use your library for a project, but encountered issues while compiling with strict-mode on:

```
node_modules/simple-crypto-js/src/SimpleCrypto.ts:9:22 - error TS7006: Parameter 'secret' implicitly has an 'any' type.

9   public constructor(secret) {
                       ~~~~~~

node_modules/simple-crypto-js/src/SimpleCrypto.ts:23:11 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

23     const string: string = typeof data == "object" ? JSON.stringify(data) : typeof data == "string" || typeof data == "number" || typeof data == 'boolean' ? data.toString() : null;
             ~~~~~~

node_modules/simple-crypto-js/src/SimpleCrypto.ts:31:77 - error TS2345: Argument of type '{ iv: string | WordArray; padding: Padding; mode: Mode; }' is not assignable to parameter of type 'CipherOption'.
  Types of property 'iv' are incompatible.
    Type 'string | WordArray' is not assignable to type 'string | undefined'.
      Type 'WordArray' is not assignable to type 'string'.

 31     const encrypted: CryptoJS.WordArray = CryptoJS.AES.encrypt(string, key, {
                                                                                ~
 32       iv: initialVector,
    ~~~~~~~~~~~~~~~~~~~~~~~~
...
 34       mode: CryptoJS.mode.CBC
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 35     });
    ~~~~~
```

I have created a MR to fix these issues, and other small issues :)

### PR DESCRIPTION
**Pull request by Vezul**
Fixes #3 

And simplifies build process - now just using tsc ;-)

### CODE REVIEW

**Comment by danang-id** [comment]
Hi, I believe that the `build` folder should be included for the sake of NPM repository. I appreciate any fix on `.gitignore`, before I could merge the PR.

**Comment by lil5** [comment]
Why add the `package-lock` file?

**Comment by danang-id** [comment]
@lil5 Yes, a lock file --such as `package-lock.json` for npm and `yarn.lock` for yarn-- is intended to be checked into source control. If you're using npm 5, you may see this on the command line: `created a lockfile as package-lock.json. You should commit this file`. [See more here.](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md)

**Comment by danang-id** [comment]
@Vezul @lil5 The thing that should **not be** ignored in commit is the `build` folder. 😊

**Pull request merged**
